imports:
    - { resource: parameters_dev.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@DoctorBundle/Resources/config/services.yml" }
    - { resource: "@AgentBundle/Resources/config/services.yml" }
    - { resource: "@PatientBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    # Block user for 30 mins when wrong enter password for 10 times
    timeout: 30
    max_count_login: 10

services:
    session.memcached:
        class: Memcached
        calls:
          - [ addServer, [ "%memcached_session_host%", "%memcached_session_port%" ]]

    session.handler.memcached:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
        arguments: ["@session.memcached", { prefix: "%memcached_session_prefix%", expiretime: "%memcached_session_expire%" }]    

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: %asset_version%
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: %session_handle%
    fragments: ~
    http_method_override: true

assetic:
    debug:          "%kernel.debug%"
    use_controller: '%kernel.debug%'
    bundles:        [ AdminBundle,AgentBundle,DoctorBundle,PatientBundle ]
    filters:
        cssrewrite: ~
# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'form/cusFields.html.twig'
    globals:
        base_url: '%base_url%'
        ga_code : '%ga_tracking_code%'
        app_env : '%app_env%'

# Doctrine Configuration
doctrine:
    dbal:
        wrapper_class: Doctrine\DBAL\Connections\MasterSlaveConnection
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        logging: true
        slaves:
            slave1:
                host:     "%database_host_slave%"
                port:     "%database_port_slave%"
                dbname:   "%database_name_slave%"
                user:     "%database_user_slave%"
                password: "%database_password_slave%"
                charset:  UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            datetime_functions:
                day: DoctrineExtensions\Query\Mysql\Day
                month: DoctrineExtensions\Query\Mysql\Month
                year: DoctrineExtensions\Query\Mysql\Year
                monthname: DoctrineExtensions\Query\Mysql\MonthName
                str_to_date: DoctrineExtensions\Query\Mysql\StrToDate
                ifelse: DoctrineExtensions\Query\Mysql\IfElse
                date: DoctrineExtensions\Query\Mysql\Date
                week: DoctrineExtensions\Query\Mysql\Week
            string_functions:
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
    port: 587
    encryption: tls

monolog:    
    handlers:       
        doctrine:
            type:     stream
            path:     "%kernel.logs_dir%/doctrine.log"
            channels: [doctrine]        
        main:
            channels: ['!doctrine']    
