<?php

namespace UtilBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AddressTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressTypeRepository extends EntityRepository
{
}
