<?php

namespace UtilBundle\Repository;

use Doctrine\ORM\EntityRepository;
use UtilBundle\Utility\Constant;
use UtilBundle\Utility\MsgUtils;

/**
 * AgentPhoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgentPhoneRepository extends EntityRepository
{
	/**
     * get phone by agent id
     * @param $params
     * @return array
     * @author toan.le
     */
    public function getAgentPhone($id){
        $results = [];
        try{
            $queryBuilder = $this->createQueryBuilder('f')
                                ->where('f.agent = :id')
                                ->setParameter('id', $id)
                                ->setFirstResult(0)
                                ->setMaxResults(1);

            $resultQuery =  $queryBuilder->getQuery()->getOneOrNullResult();
            $results['success'] = true;
            $results['data'] = $resultQuery;
            if(null == $resultQuery) {
                $results['message'] = MsgUtils::generate('msgNoData');
            } else {
                $results['message'] = null;
            }
        }catch(Exception $ex){
            $results['message'] = $ex->getMessage();
            $results['success'] = false;
        }
        return $results;
    }
}
