<?php

namespace UtilBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgentAddressRepository extends EntityRepository {

    /**
     * Find object by id
     * @param type $id
     * @return type
     */
    public function findById($id) {
        return $this->find($id);
    }

    public function getAddressByAgent($agentId){
        $queryBuilder = $this->createQueryBuilder('f');
        $queryBuilder->select('ad.line1,
                               ad.line2,
                               ad.line3,
                               ad.postalCode,
                               c.name as city,
                               s.name as state,
                               ct.name as country
                            ')
                ->innerJoin('f.address', 'ad')
                ->innerJoin('UtilBundle:City', 'c', 'WITH', 'c.id = ad.city')
                ->innerJoin('UtilBundle:State', 's', 'WITH', 's.id = c.state')
                ->innerJoin('UtilBundle:Country', 'ct', 'WITH', 'ct.id = c.country')
                ->where('f.agent = (:agentId)')
                ->setParameter('agentId', $agentId);
        $result = $queryBuilder->getQuery()->getArrayResult();
        return $result;
    }
    
    /**
     * Get address
     * @param type $addressId
     */
    public function getCountrySateCity($addressId) {
        $queryBuilder = $this->createQueryBuilder('f');
        $queryBuilder->select('f,c,s,ct')
                ->innerJoin('UtilBundle:City', 'c', 'WITH', 'c.id = f.city')
                ->innerJoin('UtilBundle:State', 's', 'WITH', 's.id = c.state')
                ->innerJoin('UtilBundle:Country', 'ct', 'WITH', 'ct.id = c.country')
                ->where('f.id = (:addressId)')
                ->setParameter('addressId', $addressId);
        $result = $queryBuilder->getQuery()->getResult();
        return $result;
    }
}
