<?php

namespace UtilBundle\Repository;

use Doctrine\ORM\EntityRepository;
use UtilBundle\Entity\AgentCustomMedicineFee;

/**
 * AgentCustomMedicineFeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgentCustomMedicineFeeRepository extends EntityRepository {

    /**
     * Finc one or create
     */
    public function findOneOrCreate(array $criteria)
    {
        $acmf = $this->findOneBy($criteria);
        $em = $this->getEntityManager();

        if (null === $acmf)
        {
            $acmf = new AgentCustomMedicineFee();
            
            if(!isset($criteria['agent'])) {
                return null;
            }
            if(isset($criteria['feeValue'])) {
                $acmf->setFeeValue($criteria['feeValue']);
            }
            if(isset($criteria['feeName'])) {
                $acmf->setFeeName($criteria['feeName']);
            }
            if(isset($criteria['feeCode'])) {
                $acmf->setFeeCode($criteria['feeCode']);
            }
            $acmf->setAgent($criteria['agent']);
            $criteria['agent']->addMinMedicineFee($acmf);

            $em->persist($acmf);
            $em->flush();
        }

        return $acmf;
    }
}
