<?php

namespace UtilBundle\Repository;

use Doctrine\DBAL\Connection;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use DoctrineExtensions\Query;
use UtilBundle\Entity\Pharmacy;
use UtilBundle\Entity\AirwayBill;
use UtilBundle\Utility\Common;
use UtilBundle\Utility\Constant;

/**
 * AirwayBillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AirwayBillRepository extends EntityRepository
{

}
