<?php

namespace UtilBundle\Repository;

use Doctrine\DBAL\Connection;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use DoctrineExtensions\Query;
use UtilBundle\Utility\Common;
use UtilBundle\Utility\Constant;

/**
 * BagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BagRepository extends EntityRepository
{
    /**
     * get list
     */
    public function getListBy($params = array())
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select("bx.masterAwbCode, bx.trackingNumber, bx.status as boxStatus, d.code as countryCode")
            ->from('UtilBundle:Bag', 'b')
            ->innerJoin('UtilBundle:Box', 'bx', 'WITH', 'bx.bag = b.id')
            ->innerJoin('bx.destination', 'd')
            ->where("d.code IN(:countryCode) AND bx.deletedOn is NULL")
            ->andWhere("bx.status NOT IN(:boxStatus)")
            ->setParameter("boxStatus", $params['ignoreBoxStatus'])
            ->setParameter("countryCode", $params['countryCode'])
        ;
        return $qb->getQuery()->getArrayResult();
    }
}
