<?php
/**
 * Created by PhpStorm.
 * User: nanang
 * Date: 14/03/19
 * Time: 9:36
 */

namespace UtilBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * BankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BankRepository extends EntityRepository
{
    /*
     * get list bank by country
     */
    public function getBankByCountry($id)
    {
        $banks = $this->findBy(array('country' => $id));
        $result = array();
        foreach ($banks as $bank) {
            $name = $bank->getName();
            $branchName = $bank->getBranchName();
            if ($branchName) {
                $name .= ' '. $branchName;
            }
            $result[$bank->getId()] = $name;
        }

        return $result;
    }
}