<?php

namespace UtilBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CustomClearanceAdminFeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomClearanceAdminFeeRepository extends EntityRepository {

    /**
     * Get Fee Setting
     * @param type $countryId
     * @return type
     * author luyen nguyen
     */
    public function getFeeSetting($countryId) {
        $queryBuilder = $this->createQueryBuilder('f');
        $queryBuilder->select('fs.fee')
                ->innerJoin('UtilBundle:FeeSetting', 'fs', 'WITH', 'f.feeSetting = fs.id')
                ->where('f.country = (:countryId)')
                ->setParameter('countryId', $countryId);
        $result = $queryBuilder->getQuery()->getOneOrNullResult();
        return $result['fee'];
    }


    /**
     * get custom clearance admin fee byt id
     * @author  thu.tranq
     * @return array
     */
    public function getCAFById($id)
    {
        $qb = $this->createQueryBuilder('fs');
        $qb->select('fs.id',
            'fs.fee',
            'fs.newFee',
            'fs.effectDate'
            )
            ->where('fs.id = :id')
            ->setParameter('id', $id)
            ->setMaxResults(1);

        return $qb->getQuery()->getOneOrNullResult();
    }


}
