<?php

namespace UtilBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DoctorIdentificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctorIdentificationRepository extends EntityRepository
{
}
