<?php

namespace UtilBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DosageFormRouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DosageFormRouteRepository extends EntityRepository
{
}
