<?php

namespace UtilBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DrugTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DrugTypeRepository extends EntityRepository
{
}
