<?php

namespace UtilBundle\Repository;

/**
 * FinancialReminderSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinancialReminderSettingRepository extends \Doctrine\ORM\EntityRepository 
{
	
}