<?php

namespace UtilBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\EntityRepository;
use UtilBundle\Utility\Constant;

/**
 * FxRateLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FxRateLogRepository extends EntityRepository {

    /**
     * get list
     */
    public function getListBy($params)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('f')
            ->from('UtilBundle:FxRateLog', 'f')
            ->where('MONTH(f.createOn) = :month AND YEAR(f.createOn) = :year')
            ->setParameter('month', (int)$params['month'])
            ->setParameter('year', (int)$params['year'])
            ->orderBy('f.createOn', 'DESC');
        $list = $qb->getQuery()->getArrayResult();
        $result = array();
        if(!empty($list)) {
            foreach($list as $v) {
                $result[$v['createOn']->format('Ymd')]['createOn'] = $v['createOn'];
                $result[$v['createOn']->format('Ymd')]['rate'.$v['currencyTo']] = $v['rate'];
            }
        }
        return $result;
    }
}
