<?php

namespace UtilBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IdentificationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdentificationTypeRepository extends EntityRepository
{
}
