<?php

namespace UtilBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IdentificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdentificationRepository extends EntityRepository
{
}
