<?php

namespace UtilBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicalSpecialtyRepository extends EntityRepository {

	public function findAll(){
        return $this->findBy(array(), array('name' => 'ASC'));
    }

    public function getMedicalSpecality() {
        $data = $this->findAll();
        $result = array();
        foreach ($data as $record) {
            $result[$record->getId()] = $record->getName();
        }
        return $result;
    }

}
