<?php

namespace UtilBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MedicalLicenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicalLicenseRepository extends EntityRepository
{
}
