<?php

namespace UtilBundle\Repository;

use Doctrine\ORM\EntityRepository;
use UtilBundle\Utility\Constant;
use UtilBundle\Entity\MessageContent;
use \Datetime;

/**
 * MessageContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageContentRepository extends EntityRepository
{
    /**
     * create new
     * @author vinh.nguyen
     */
    public function create($params)
    {
        $content = new MessageContent();
        $content->setSubject($params['subject']);
        $content->setBody($params['body']);
        $content->setCreatedOn(new \DateTime());

        $em = $this->getEntityManager();
        $em->persist($content);
        $em->flush();
        
        return $content;
    }
}
