<?php

namespace UtilBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PatientAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientAddressRepository extends EntityRepository {

    /**
     * Get addresses patient
     * @param type $patientId
     * @return type
     */
    public function getAddresses($patientId) {
        $queryBuilder = $this->createQueryBuilder('f');
        $queryBuilder
                ->where('f.patient = (:patientId)')
                ->setParameter('patientId', $patientId);
        $resultQuery = $queryBuilder->getQuery()->getResult();
        return $resultQuery;
    }  
}
