<?php

namespace UtilBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use DoctrineExtensions\Query;
use UtilBundle\Entity\PharmacyPoDailyLine;

/**
 * PharmacyPoDailyLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PharmacyPoDailyLineRepository extends EntityRepository
{
    /**
     * create new
     * @author vinh.nguyen
     */
    public function create($params)
    {
        $podLineObj = new PharmacyPoDailyLine();
        $podLineObj->setRx($params['rx']);
        $podLineObj->setPoDaily($params['poDaily']);
        $podLineObj->setCreatedOn(new \DateTime());

        $em = $this->getEntityManager();
        $em->persist($podLineObj);
        $em->flush();

        return $podLineObj->getId();
    }
    
    /**
     * update
     * @author vinh.nguyen
     */
    public function update($id, $poDailyObj)
    {
        $podLineObj = $this->find($id);
        if( null == $podLineObj )
            return null;

        $podLineObj->setPoDaily($poDailyObj);

        $em = $this->getEntityManager();
        $em->persist($podLineObj);
        $em->flush();

        return $podLineObj->getId();
    }
}