<?php

namespace UtilBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PhoneTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneTypeRepository extends EntityRepository {

    public function getPhone() {
        $query = $this->createQueryBuilder('p')
                ->setMaxResults(1)
                ->orderBy('p.id')
                ->getQuery();
        $phoneType = $query->getSingleResult();
        
        return $phoneType;
    }

}
