<?php

namespace UtilBundle\Repository;

/**
 * ResolveRedispenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResolveRedispenseRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRedispenseForDate($date) {

        $queryBuilder = $this->createQueryBuilder('f')
            ->innerJoin('f.resolve','r')
            ->where('date(f.createdOn) = :date')
            ->andWhere('r.status  = 1')
            ->andWhere('r.deletedOn  is null')
            ->setParameter('date',$date);

        $result = $queryBuilder->getQuery()->getResult();
        return $result;


    }
}
