<?php

namespace UtilBundle\Repository;

/**
 * ResolveTrackingCompletedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResolveTrackingCompletedRepository extends \Doctrine\ORM\EntityRepository
{
    
}
