<?php

namespace UtilBundle\Repository;

/**
 * ResolveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResolveRepository extends \Doctrine\ORM\EntityRepository
{
    public function getResolveForDate($date) {

        $queryBuilder = $this->createQueryBuilder('f')
            ->leftJoin('f.resolveRedispenses','r')
            ->leftJoin('f.resolveParcels','p')
            ->where('date(f.createdOn) = :date')
            ->andWhere('f.status  = 1')
            ->andWhere('f.deletedOn  is null')
            ->setParameter('date',$date);

        $result = $queryBuilder->getQuery()->getResult();
        return $result;


    }
}
