<?php

namespace UtilBundle\Repository;

/**
 * RxLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RxLogRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRxForDate($date) {

        $queryBuilder = $this->createQueryBuilder('f')
            ->innerJoin('f.rx','rx')
            ->where('date(f.updatedOn) = :date')
            ->andWhere('f.delivered = 1')
            ->setParameter('date',$date);

        $result = $queryBuilder->getQuery()->getResult();
        return $result;


    }
}
