<?php

namespace UtilBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SequenceNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SequenceNumberRepository extends EntityRepository {
    
    /**
     * Find by id
     * author luyen nguyen
     */
    public function findById($id) {
        return $this->find($id);
    }
    
}
