<?php

namespace UtilBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StateRepository extends EntityRepository {

    /*
     * author bien
     */
    public function getCityByState($id) {
        $state = $this->find($id);

        $result = array();
        if (empty($state)) {
            return $result;
        }
        $cities = $state->getCities();
        foreach ($cities as $city) {
            $result[$city->getId()] = $city->getName();
        }
        
        return $result;
    }

    /*
    * author bien
    */
    public function getCityByStateCC($id) {
        $state = $this->find($id);

        $result = array();
        if (empty($state)) {
            return $result;
        }
        $cities = $state->getCities();
        foreach ($cities as $city) {
            $result[] = ['id' => $city->getId(), 'name' => $city->getName()];
        }

        return $result;
    }
    /*
     * get all state
     */

    public function getListState($countryId) {
        $result = array();
        if(empty($countryId)){
            return $result;
        }
        $queryBuilder = $this->createQueryBuilder('f');
        $queryBuilder->select('f')
            ->where('c.country IN (:ids)')
            ->innerJoin('f.cities','c')
            ->setParameter('ids', $countryId);
        $data = $queryBuilder->getQuery()->getResult();

        foreach ($data as $c) {
            $result[$c->getId()] = $c->getName();
        }
        
        return $result;
    }

}
