<?php

namespace UtilBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TherapeuticIndexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TherapeuticIndexRepository extends EntityRepository
{
}
