<?php

namespace UtilBundle\Repository;

/**
 * XeroSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XeroSettingRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * get platform setting
     * @author  thu.tranq
     * @return array
     */
    public function getXeroSetting() {
        $queryBuilder = $this->createQueryBuilder('a');
        $queryBuilder->setMaxResults(1);
        return $queryBuilder->getQuery()->getOneOrNullResult();
    }

}
