<?php

namespace UtilBundle\Repository;
use UtilBundle\Utility\Constant;

/**
 * XeroSaleLineSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XeroSaleLineSourceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSaleForSettlement(){
        $queryBuilder = $this->createQueryBuilder('f');
        $queryBuilder->select('f.rxInvoiceId as rxId, rx.orderNumber as orderNumber, sync.xeroGuid as guid, p.id as patientId, sync.id as syncId')
            ->innerJoin('UtilBundle:Rx','rx','WITH', 'rx.id = f.rxInvoiceId')
            ->innerJoin('f.xeroSaleLine','l')
            ->innerJoin('l.xeroSale','s')
            ->innerJoin('s.xeroSyncData','sync')
            ->innerJoin('rx.patient','p')
            ->where($queryBuilder->expr()->eq('s.isCreatedSaleSettlement','0').' or '.$queryBuilder->expr()->isNull('s.isCreatedSaleSettlement') )
            ->andWhere($queryBuilder->expr()->eq('sync.isSynced', true))
            ->groupBy('rxId');

        $result = $queryBuilder->getQuery()->getArrayResult();
        return $result;

    }
}
