<?php

namespace UtilBundle\Repository;

/**
 * XeroStatementTrackingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XeroStatementTrackingRepository extends \Doctrine\ORM\EntityRepository
{
    public function getItemUsed($param){
        $qb = $this->createQueryBuilder('s');
        $qb->where($qb->expr()->eq('s.statementId', $param['id']))
            ->andWhere($qb->expr()->eq('s.statementType', $param['type']))
            ->andWhere($qb->expr()->eq('s.functionName', "'".$param['function']."'"))
            ->andWhere($qb->expr()->eq('s.siteCode', "'".$param['code']."'"))
            ->andwhere($qb->expr()->eq('DATE(s.trackingDate)', "'".$param['date']."'"))
            ->andWhere($qb->expr()->isNull("s.deletedOn"))
            ->setMaxResults(1);
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getItemForDelete($date){
        $qb = $this->createQueryBuilder('s');
        $qb->where($qb->expr()->eq('DATE(s.trackingDate)', "'".$date."'"));
        return $qb->getQuery()->getResult();
    }
}
