<?php

namespace UtilBundle\Repository;

/**
 * XeroCoaVersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XeroCoaVersionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDataForDate($date) {

        $queryBuilder = $this->createQueryBuilder('c');
        $queryBuilder
        ->where($queryBuilder->expr()->eq("date(c.effectiveDate)", "'".$date."'"));

        $result = $queryBuilder->getQuery()->getOneOrNullResult();
        return $result;
    }
}
