<?php

namespace UtilBundle\Repository;
use UtilBundle\Utility\Constant;

/**
 * XeroBillLineSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XeroBillLineSourceRepository extends \Doctrine\ORM\EntityRepository
{
}
